server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        # Tente de servir le fichier, sinon le dossier, sinon renvoie sur index.html
        try_files $uri $uri/ /index.html;
    }
}
