spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.ip=${pg_ip:db}
spring.datasource.port=${pg_port:5432}
spring.datasource.bdd=${pg_bdd:service_worker}
spring.datasource.url=jdbc:postgresql://${pg_ip:db}:${pg_port:5432}/${pg_bdd:service_worker}

spring.jpa.show-sql=false